services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    networks:
      - backend
    ports:
      - "5432:5432"
    volumes:
      - api-db:/var/lib/postgresql/data

networks:
  backend: {}

volumes:
  api-db: {}
