
services:

  web:
    image: ameliaah/ehb:enterprise-applications
    environment:
      - "DB=postgres"
    networks:
      - backend
    ports:
      - "80:8080"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    networks:
      - backend
    ports:
      - "5431:5432"
    volumes:
      - api-db:/var/lib/postgresql/data

networks:
  backend: {}

volumes:
  api-db: {}
